service: url-hasher
frameworkVersion: '3'
plugins:
  - serverless-offline
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    MONGO_URI: ${file(./secret.json):MONGO_URI}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'